export default {
	INVALID_ITEM: 0,
	VALID_ITEM: 1,
	PENDING_WHILE_IMPORT_UNDERWAY: 2,
	PENDING_ORDER_NEEDS_TO_BE_PLACED: 3,
  TEST_ORDER: 4,
  ITEM_OUT_OF_STOCK: 5,
  ITEM_NOT_AVAILABLE_AS_ORDERED: 6,
  ITEM_RETURNED: 7,
  EXCEPTION_AUTOMATED_ORDER_COULDNT_BE_PLACED: 8,
  PENDING_ORDER_IS_BEING_PLACED: 9,
  PARTIALLY_COMPLETED_ORDER: 10,
  SUCCESSFULLY_COMPLETED_ORDER: 11,
  ORDER_ITEM_PROCESSED_SUCCESSFULLY: 12,
  ORDER_ITEM_NOT_PROCESSED_DUE_ORDER_FAILURE: 13,
  ORDER_ITEM_NOT_PROCESSED_DUE_SITE_FAILURE: 14
}